export const products = [
  {
    id: '1',
    name: 'Vestido Midi Floral Manga Bufante',
    price: 89.90,
    originalPrice: 139.90,
    tag: 'Novo',
    badge: '🔥 Mais vendido',
    urgency: 'Restam poucas unidades',
    colors: ['#2d2d2d', '#e8b4b8', '#f0e6e0'],
    category: 'vestidos',
    sizes: ['P', 'M', 'G', 'GG'],
    sold: 347,
    rating: 4.9,
    reviews: 89,
    description: 'Vestido midi com estampa floral delicada, manga bufante e cintura marcada. Tecido leve e fluido, perfeito para o dia a dia com um toque de elegância. Composição: 95% viscose, 5% elastano.',
  },
  {
    id: '2',
    name: 'Blusa Cropped Canelada Off-White',
    price: 49.90,
    originalPrice: 79.90,
    tag: 'Novo',
    badge: '💖 Favorito',
    urgency: 'Alta procura hoje',
    colors: ['#f0e6e0', '#2d2d2d', '#c9969a'],
    category: 'blusas',
    sizes: ['P', 'M', 'G'],
    sold: 523,
    rating: 4.8,
    reviews: 134,
    description: 'Blusa cropped em malha canelada, com acabamento premium e caimento perfeito. Versátil para compor looks casuais ou mais elaborados. Composição: 90% algodão, 10% elastano.',
  },
  {
    id: '3',
    name: 'Calça Wide Leg Alfaiataria Preta',
    price: 99.90,
    originalPrice: 159.90,
    tag: 'Promo',
    badge: '🔥 Mais vendido',
    urgency: 'Acabando rápido',
    colors: ['#2d2d2d', '#f0e6e0'],
    category: 'calcas',
    sizes: ['36', '38', '40', '42', '44'],
    sold: 891,
    rating: 4.9,
    reviews: 267,
    description: 'Calça wide leg em tecido de alfaiataria com caimento impecável. Cintura alta com pregas frontais que alongam a silhueta. Composição: 97% poliéster, 3% elastano.',
  },
  {
    id: '4',
    name: 'Sandália Rasteira Tiras Douradas',
    price: 69.90,
    originalPrice: 99.90,
    tag: null,
    badge: '💖 Favorito',
    urgency: 'Restam poucas unidades',
    colors: ['#d4a574', '#2d2d2d'],
    category: 'calcados',
    sizes: ['35', '36', '37', '38', '39'],
    sold: 412,
    rating: 4.7,
    reviews: 98,
    description: 'Sandália rasteira com tiras finas em material metalizado dourado. Conforto e sofisticação para o dia a dia. Palmilha macia anatômica.',
  },
  {
    id: '5',
    name: 'Conjunto Saia + Cropped Linho',
    price: 119.90,
    originalPrice: 179.90,
    tag: 'Novo',
    badge: '🔥 Mais vendido',
    urgency: 'Alta procura hoje',
    colors: ['#f0e6e0', '#c9969a'],
    category: 'conjuntos',
    sizes: ['P', 'M', 'G'],
    sold: 276,
    rating: 5.0,
    reviews: 73,
    description: 'Conjunto de saia midi e cropped em linho premium. Ideal para looks frescos e elegantes de verão. Composição: 100% linho.',
  },
  {
    id: '6',
    name: 'Bolsa Transversal Matelassê',
    price: 79.90,
    originalPrice: 129.90,
    tag: 'Promo',
    badge: null,
    urgency: 'Acabando rápido',
    colors: ['#2d2d2d', '#e8b4b8', '#f0e6e0'],
    category: 'acessorios',
    sizes: ['Único'],
    sold: 634,
    rating: 4.8,
    reviews: 189,
    description: 'Bolsa transversal em material matelassê com acabamento premium. Alça ajustável e fecho magnético. Interior forrado com bolso.',
  },
  {
    id: '7',
    name: 'Vestido Tubinho Preto Essencial',
    price: 79.90,
    originalPrice: 119.90,
    tag: null,
    badge: '🔥 Mais vendido',
    urgency: 'Restam poucas unidades',
    colors: ['#2d2d2d'],
    category: 'vestidos',
    sizes: ['P', 'M', 'G', 'GG'],
    sold: 1023,
    rating: 4.9,
    reviews: 312,
    description: 'O clássico vestido tubinho preto, peça indispensável no guarda-roupa. Tecido com elastano para conforto e modelagem perfeita.',
  },
  {
    id: '8',
    name: 'Saia Midi Plissada Rosa Antigo',
    price: 69.90,
    originalPrice: 99.90,
    tag: 'Novo',
    badge: '💖 Favorito',
    urgency: null,
    colors: ['#c9969a', '#2d2d2d', '#f0e6e0'],
    category: 'saias',
    sizes: ['P', 'M', 'G'],
    sold: 198,
    rating: 4.7,
    reviews: 56,
    description: 'Saia midi plissada em tom rosa antigo, com cintura elástica e caimento fluido. Elegância atemporal para qualquer ocasião.',
  },
  {
    id: '9',
    name: 'Blazer Oversized Bege Estruturado',
    price: 109.90,
    originalPrice: 169.90,
    tag: null,
    badge: null,
    urgency: 'Alta procura hoje',
    colors: ['#d4b896', '#2d2d2d'],
    category: 'blazers',
    sizes: ['P', 'M', 'G'],
    sold: 345,
    rating: 4.8,
    reviews: 87,
    description: 'Blazer oversized em tecido estruturado na cor bege. Com forro interno, bolsos frontais e fechamento com um botão.',
  },
  {
    id: '10',
    name: 'Tênis Casual Branco Plataforma',
    price: 89.90,
    originalPrice: 149.90,
    tag: 'Promo',
    badge: '🔥 Mais vendido',
    urgency: 'Acabando rápido',
    colors: ['#ffffff', '#e8b4b8'],
    category: 'calcados',
    sizes: ['35', '36', '37', '38', '39'],
    sold: 756,
    rating: 4.9,
    reviews: 234,
    description: 'Tênis casual branco com solado plataforma de 3cm. Confortável, moderno e combina com tudo. Palmilha memory foam.',
  },
  {
    id: '11',
    name: 'Macacão Pantacourt Linho Natural',
    price: 99.90,
    originalPrice: 149.90,
    tag: null,
    badge: '💖 Favorito',
    urgency: null,
    colors: ['#f0e6e0', '#2d2d2d'],
    category: 'macacao',
    sizes: ['P', 'M', 'G'],
    sold: 287,
    rating: 4.6,
    reviews: 64,
    description: 'Macacão pantacourt em linho natural com botões frontais e amarração na cintura. Peça coringa para o verão.',
  },
  {
    id: '12',
    name: 'Short Alfaiataria Cintura Alta',
    price: 59.90,
    originalPrice: 89.90,
    tag: 'Novo',
    badge: null,
    urgency: 'Restam poucas unidades',
    colors: ['#2d2d2d', '#f0e6e0', '#c9969a'],
    category: 'shorts',
    sizes: ['36', '38', '40', '42'],
    sold: 432,
    rating: 4.8,
    reviews: 112,
    description: 'Short de alfaiataria com cintura alta e pregas frontais. Visual sofisticado com todo o conforto que você merece.',
  },
]

export const lookProducts = [
  {
    id: '5',
    name: 'Conjunto Saia + Cropped Linho',
    price: 119.90,
    label: 'Conjunto',
  },
  {
    id: '4',
    name: 'Sandália Rasteira Tiras Douradas',
    price: 69.90,
    label: 'Calçado',
  },
  {
    id: '6',
    name: 'Bolsa Transversal Matelassê',
    price: 79.90,
    label: 'Acessório',
  },
]

export const socialProof = [
  { name: '@maria.style', text: 'Amei a qualidade! Chegou super rápido e o tecido é maravilhoso. Virei cliente fiel!', rating: 5, product: 'Vestido Midi Floral' },
  { name: '@ana.looks', text: 'Peças incríveis! O acabamento é perfeito, parece roupa de grife. Já fiz 3 pedidos esse mês.', rating: 5, product: 'Calça Wide Leg' },
  { name: '@julia.moda', text: 'O vestido ficou perfeito, exatamente como na foto. Recebi muitos elogios!', rating: 5, product: 'Vestido Tubinho Preto' },
  { name: '@carol.fashion', text: 'Melhor loja online que já comprei. Entrega rápida, embalagem linda e peças de qualidade.', rating: 5, product: 'Conjunto Linho' },
  { name: '@bea.closet', text: 'Tecido maravilhoso, acabamento impecável. O blazer é PERFEITO. Superou minhas expectativas!', rating: 4, product: 'Blazer Oversized' },
  { name: '@lu.estilo', text: 'Frete grátis e chegou antes do prazo! A bolsa é linda, muito bem feita. Super recomendo!', rating: 5, product: 'Bolsa Matelassê' },
]

export function getProductById(id) {
  return products.find((p) => p.id === id)
}

export function getRelatedProducts(id, limit = 4) {
  const product = getProductById(id)
  if (!product) return products.slice(0, limit)
  return products
    .filter((p) => p.id !== id && p.category === product.category)
    .concat(products.filter((p) => p.id !== id && p.category !== product.category))
    .slice(0, limit)
}
